In [34]:
import pandas as pd
import numpy as np

In [35]:
#pd.set_option('display.notebook_repr_html', True)
#pd.set_option('display.max_columns', 8)
#pd.set_option('display.max_rows', 8)

---------
# Series

In [36]:
s = pd.Series(np.random.rand(10))

In [37]:
s

0    0.127570
1    0.275211
2    0.081847
3    0.771748
       ...   
6    0.609570
7    0.388638
8    0.937978
9    0.866198
Length: 10, dtype: float64

In [38]:
s.index

RangeIndex(start=0, stop=10, step=1)

In [39]:
s.values

array([0.12756983, 0.27521071, 0.08184671, 0.77174824, 0.96075516,
       0.88900441, 0.60956984, 0.38863826, 0.93797766, 0.86619834])

In [40]:
s = pd.Series([1,2,3,4], index=['a','b','c','d'])

In [41]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [42]:
k = s.append(pd.Series(5)) 
k

a    1
b    2
c    3
d    4
0    5
dtype: int64

In [43]:
k.shape

(5,)

In [44]:
k.count()

5

In [45]:
k.unique()

array([1, 2, 3, 4, 5])

In [46]:
k.value_counts()

1    1
2    1
3    1
4    1
5    1
dtype: int64

In [47]:
s3 = pd.Series([1,2,3,4], index=['a','b','c','d'])
s3

a    1
b    2
c    3
d    4
dtype: int64

In [48]:
s4 = pd.Series([4,3,2,1], index=['d','c','b','a'])
s4

d    4
c    3
b    2
a    1
dtype: int64

In [49]:
s3 + s4

a    2
b    4
c    6
d    8
dtype: int64

---------
# DataFrames

In [50]:
df = pd.DataFrame(np.array([[10,11], [20,21]]))
df


0   1
0  10  11
1  20  21

In [51]:
df.index= ['a','b']
df

0   1
a  10  11
b  20  21

In [52]:
df.columns=['x','y']
df

x   y
a  10  11
b  20  21

In [53]:
df1 = pd.DataFrame([pd.Series(np.arange(10,15)),
                    pd.Series(np.arange(15,20))])
df1

0   1   2   3   4
0  10  11  12  13  14
1  15  16  17  18  19

In [54]:
df1.shape

(2, 5)

In [55]:
df.columns = ['c1', 'c2']
df 

c1  c2
a  10  11
b  20  21

In [56]:
df.index

Index(['a', 'b'], dtype='object')

In [57]:
df.values

array([[10, 11],
       [20, 21]])

-----------

In [58]:
s1 = pd.Series(np.arange(1,6,1))
s2 = pd.Series(np.arange(6,11,1))
s3 = pd.Series(np.arange(12,14), index=[1,2])
pd.DataFrame({'c1':s1, 'c2':s2, 'c3': s3})

c1  c2    c3
0   1   6   NaN
1   2   7  12.0
2   3   8  13.0
3   4   9   NaN
4   5  10   NaN

-----------
# Example 

In [61]:
sp500 = pd.read_csv("../data/sp500.csv")
sp500.head()

Symbol                 Name                  Sector   Price  ...  EBITDA  \
0    MMM               3M Co.             Industrials  141.14  ...   8.121   
1    ABT  Abbott Laboratories             Health Care   39.60  ...   4.359   
2   ABBV          AbbVie Inc.             Health Care   53.95  ...   7.190   
3    ACN            Accenture  Information Technology   79.79  ...   4.423   
4    ACE          ACE Limited              Financials  102.91  ...   4.275   

   Price/Sales  Price/Book                                        SEC Filings  
0         2.95        5.26  http://www.sec.gov/cgi-bin/browse-edgar?action...  
1         2.74        2.55  http://www.sec.gov/cgi-bin/browse-edgar?action...  
2         4.48       18.16  http://www.sec.gov/cgi-bin/browse-edgar?action...  
3         1.75        9.54  http://www.sec.gov/cgi-bin/browse-edgar?action...  
4         1.79        1.18  http://www.sec.gov/cgi-bin/browse-edgar?action...  

[5 rows x 15 columns]

In [62]:
sp500.describe()

Price  Dividend Yield  Price/Earnings  Earnings/Share  ...  \
count   500.00000      424.000000      480.000000      499.000000  ...   
mean     77.36860        2.131439       29.887792        3.564842  ...   
std      87.59694        1.321017       70.163577        4.049497  ...   
min       0.00000        0.040000        2.520000      -10.693000  ...   
25%      38.74500        1.260000       15.570000        1.652000  ...   
50%      58.35500        1.890000       20.005000        2.841000  ...   
75%      86.68000        2.820000       26.627500        4.435000  ...   
max    1197.12000       10.640000     1329.620000       41.727000  ...   

       Market Cap      EBITDA  Price/Sales  Price/Book  
count  496.000000  499.000000   496.000000  486.000000  
mean    35.348525    3.700364     2.782359    4.620514  
std     54.839169    6.669021     2.529481   10.578663  
min      0.208500   -0.331300     0.000000    0.000000  
25%      9.859250    0.867800     1.220000    1.802500  
50%     17.444500    1.636000     2.005000    3.125000  
75%     34.653250    3.793500     3.377500    4.730000  
max    529.000000   60.657000    17.840000  213.740000  

[8 rows x 11 columns]

In [65]:
sp500.columns

Index(['Symbol', 'Name', 'Sector', 'Price', 'Dividend Yield', 'Price/Earnings',
       'Earnings/Share', 'Book Value', '52 week low', '52 week high',
       'Market Cap', 'EBITDA', 'Price/Sales', 'Price/Book', 'SEC Filings'],
      dtype='object')

In [67]:
sp500.index = sp500["Symbol"]

In [68]:
sp500.index

Index(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ACT', 'ADBE', 'AES', 'AET', 'AFL',
       ...
       'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZMH', 'ZION', 'ZTS'],
      dtype='object', name='Symbol', length=500)

In [69]:
sp500.head()

Symbol                 Name                  Sector   Price  ...  \
Symbol                                                              ...   
MMM       MMM               3M Co.             Industrials  141.14  ...   
ABT       ABT  Abbott Laboratories             Health Care   39.60  ...   
ABBV     ABBV          AbbVie Inc.             Health Care   53.95  ...   
ACN       ACN            Accenture  Information Technology   79.79  ...   
ACE       ACE          ACE Limited              Financials  102.91  ...   

        EBITDA  Price/Sales  Price/Book  \
Symbol                                    
MMM      8.121         2.95        5.26   
ABT      4.359         2.74        2.55   
ABBV     7.190         4.48       18.16   
ACN      4.423         1.75        9.54   
ACE      4.275         1.79        1.18   

                                              SEC Filings  
Symbol                                                     
MMM     http://www.sec.gov/cgi-bin/browse-edgar?action...  
ABT     http://www.sec.gov/cgi-bin/browse-edgar?action...  
ABBV    http://www.sec.gov/cgi-bin/browse-edgar?action...  
ACN     http://www.sec.gov/cgi-bin/browse-edgar?action...  
ACE     http://www.sec.gov/cgi-bin/browse-edgar?action...  

[5 rows x 15 columns]

-----------
# Selecting Columns

In [125]:
sp500[sp500.columns[1:3]]

Name                  Sector
Symbol                                             
MMM                  3M Co.             Industrials
ABT     Abbott Laboratories             Health Care
ABBV            AbbVie Inc.             Health Care
ACN               Accenture  Information Technology
...                     ...                     ...
YUM         Yum! Brands Inc  Consumer Discretionary
ZMH         Zimmer Holdings             Health Care
ZION          Zions Bancorp              Financials
ZTS              Zoetis Inc             Health Care

[500 rows x 2 columns]

In [127]:
sp500['Price']

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
         ...  
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, Length: 500, dtype: float64

In [128]:
sp500.Price

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
         ...  
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, Length: 500, dtype: float64

----------
# Selecting Rows

In [131]:
sp500[1:2]

Symbol                 Name       Sector  Price  ...  EBITDA  \
Symbol                                                  ...           
ABT       ABT  Abbott Laboratories  Health Care   39.6  ...   4.359   

        Price/Sales  Price/Book  \
Symbol                            
ABT            2.74        2.55   

                                              SEC Filings  
Symbol                                                     
ABT     http://www.sec.gov/cgi-bin/browse-edgar?action...  

[1 rows x 15 columns]

In [137]:
sp500['XYL':'YUM']

Symbol             Name                  Sector  Price  ...  EBITDA  \
Symbol                                                         ...           
XYL       XYL       Xylem Inc.             Industrials  38.42  ...  0.6150   
YHOO     YHOO       Yahoo Inc.  Information Technology  35.02  ...  0.8873   
YUM       YUM  Yum! Brands Inc  Consumer Discretionary  74.77  ...  2.8640   

        Price/Sales  Price/Book  \
Symbol                            
XYL            1.80        3.13   
YHOO           7.48        2.72   
YUM            2.49       14.55   

                                              SEC Filings  
Symbol                                                     
XYL     http://www.sec.gov/cgi-bin/browse-edgar?action...  
YHOO    http://www.sec.gov/cgi-bin/browse-edgar?action...  
YUM     http://www.sec.gov/cgi-bin/browse-edgar?action...  

[3 rows x 15 columns]

### Locate (df.iloc and df.loc) by index and by row label, respectively

In [146]:
sp500.iloc[45]

Symbol                                                      ADSK
Name                                                Autodesk Inc
Sector                                    Information Technology
Price                                                       52.0
                                     ...                        
EBITDA                                                    0.3922
Price/Sales                                                  5.1
Price/Book                                                  5.12
SEC Filings    http://www.sec.gov/cgi-bin/browse-edgar?action...
Name: ADSK, Length: 15, dtype: object

In [152]:
sp500.loc['ADSK']

Symbol                                                      ADSK
Name                                                Autodesk Inc
Sector                                    Information Technology
Price                                                       52.0
                                     ...                        
EBITDA                                                    0.3922
Price/Sales                                                  5.1
Price/Book                                                  5.12
SEC Filings    http://www.sec.gov/cgi-bin/browse-edgar?action...
Name: ADSK, Length: 15, dtype: object

In [154]:
sp500.loc[['MMM', 'MSFT']]

Symbol             Name                  Sector   Price  ...  EBITDA  \
Symbol                                                          ...           
MMM       MMM           3M Co.             Industrials  141.14  ...   8.121   
MSFT     MSFT  Microsoft Corp.  Information Technology   40.12  ...  32.127   

        Price/Sales  Price/Book  \
Symbol                            
MMM            2.95        5.26   
MSFT           3.97        3.79   

                                              SEC Filings  
Symbol                                                     
MMM     http://www.sec.gov/cgi-bin/browse-edgar?action...  
MSFT    http://www.sec.gov/cgi-bin/browse-edgar?action...  

[2 rows x 15 columns]

In [155]:
sp500.iloc[[0,2]]

Symbol         Name       Sector   Price  ...  EBITDA  Price/Sales  \
Symbol                                           ...                        
MMM       MMM       3M Co.  Industrials  141.14  ...   8.121         2.95   
ABBV     ABBV  AbbVie Inc.  Health Care   53.95  ...   7.190         4.48   

        Price/Book                                        SEC Filings  
Symbol                                                                 
MMM           5.26  http://www.sec.gov/cgi-bin/browse-edgar?action...  
ABBV         18.16  http://www.sec.gov/cgi-bin/browse-edgar?action...  

[2 rows x 15 columns]

In [156]:
sp500.iloc[0]

Symbol                                                       MMM
Name                                                      3M Co.
Sector                                               Industrials
Price                                                     141.14
                                     ...                        
EBITDA                                                     8.121
Price/Sales                                                 2.95
Price/Book                                                  5.26
SEC Filings    http://www.sec.gov/cgi-bin/browse-edgar?action...
Name: MMM, Length: 15, dtype: object

In [157]:
sp500.loc['A']

Symbol                                                         A
Name                                    Agilent Technologies Inc
Sector                                               Health Care
Price                                                      56.18
                                     ...                        
EBITDA                                                     1.396
Price/Sales                                                 2.73
Price/Book                                                  3.28
SEC Filings    http://www.sec.gov/cgi-bin/browse-edgar?action...
Name: A, Length: 15, dtype: object

#### Look up a scalar by column and row label or location (df.at[] and df.iat[])

In [161]:
sp500.at['MSFT', 'Price']

40.12

In [162]:
sp500.iat[0,1]

'3M Co.'

------------
# Boolean selection

----------
# Arithetic on dataframes

-----------
# Reindexing